In [1]:
from transformers import TFOpenAIGPTLMHeadModel

model = TFOpenAIGPTLMHeadModel.from_pretrained("openai-gpt")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFOpenAIGPTLMHeadModel: ['h.3.attn.bias', 'h.8.attn.bias', 'h.9.attn.bias', 'h.1.attn.bias', 'h.0.attn.bias', 'h.11.attn.bias', 'h.4.attn.bias', 'h.10.attn.bias', 'h.2.attn.bias', 'h.7.attn.bias', 'h.6.attn.bias', 'h.5.attn.bias']
- This IS expected if you are initializing TFOpenAIGPTLMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFOpenAIGPTLMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFOpenAIGPTLMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFOpenAIGPTLMHeadModel for predicti

In [2]:
from transformers import OpenAIGPTTokenizer

tokenizer = OpenAIGPTTokenizer.from_pretrained("openai-gpt")

ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.


In [3]:
tokenizer("hello everyone")

{'input_ids': [3570, 1473], 'attention_mask': [1, 1]}

In [4]:
prompt_text = "This royal throne of kings, this sceptred isle"
encoded_prompt = tokenizer.encode(prompt_text,
                                  add_special_tokens=False,
                                  return_tensors="tf")
encoded_prompt

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187]], dtype=int32)>

In [5]:
num_sequences = 5
length = 40

generated_sequences = model.generate(
    input_ids=encoded_prompt,
    do_sample=True,
    max_length=length + len(encoded_prompt[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    repetition_penalty=1.0,
    num_return_sequences=num_sequences,
)

generated_sequences

<tf.Tensor: shape=(5, 50), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   239,   616,  2399,   498,   946, 32995,   544,   246,
        18493,   498,  9014,   240,   500,  2255,   498,   481,  1618,
          525,   507,   597,   980,   566,  1803,   999,   781,   520,
        15346,   240,   568,   520,   544,   843, 18044,   240,   488,
          812,  3423,   485,  4097,   669],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   239,   244, 40477,   244,   249,   668,   823,   485,
         3545,   599,   535,  3155,   240,   244,   249,  1530,   488,
          674,   603,   240,   244,  1572,   972,   510,   525,   512,
          604,   246,  6508,   525,   759, 22601,  7449,  6529,   239,
          244, 40477,   244,   600,   604],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   239,   481,   869, 11090,   742,   636,  1578,   481,
         6404

In [6]:
for sequence in generated_sequences:
    text = tokenizer.decode(sequence, clean_up_tokenization_spaces=True)
    print(text)
    print("-" * 80)

this royal throne of kings, this sceptred isle. this piece of monarchs is a token of loyalty, in view of the fact that it now has one year left before she sinks, but she is still ambitious, and will continue to grow when
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle. " 
 " i just want to enjoy what's happening, " i lied and then said, " please tell me that you have a device that can render dragons unconscious. " 
 " they have
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle. the angaraks would hold the throne themselves. the asturian archers would mount their well - trained attack. then, after the campaign was done, a large number of asturians, lamor
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle has disappeared for good. as you said, he has been k